apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=         # base64 for "username"
  POSTGRES_PASSWORD: cG9zdGdyZXM=     # base64 for "password"
